### ISSUE TITLE
day这个参数好像没用啊

### ISSUE THREAD

**Issue by ahmczsy** [Jaggle/Gitfool#1]
这个需要写个cron每天执行一遍吗？

**Comment by jjsty1e** [comment]
1. 需要的，days这个参数是指定要给过去的多少天提交commit，比如365可以指定最近的一年
2. 不需要cron，是为过去生成commit，而不是将来

**Comment by ahmczsy** [comment]
我执行这个命令后
```bash
./gitfool path 365 --push
```
一直提示这个信息
Try 'date --help' for more information.
date: invalid option -- 'v'

之后提示完成后，我看了下commit log 都是同一天的commit
是我用的姿势不对吗

**Comment by jjsty1e** [comment]
你的path不对啊，path也是一个变量，是你git仓库的目录

**Comment by jjsty1e** [comment]
@ahmczsy 在你的仓库目录执行下面的代码也行：

```bash
curl -s https://raw.githubusercontent.com/Jaggle/Gitfool/master/gitfool| sh -s `pwd` 365 --push
```

**Comment by ahmczsy** [comment]
我知道path是变量，在我执行的时候是仓库目录
```bash
curl -s https://raw.githubusercontent.com/Jaggle/Gitfool/master/gitfool| sh -s `pwd` 365 --push
```
在仓库目录下执行这个命令还是提示同样的错误

![img](https://user-images.githubusercontent.com/37166916/41635270-73db62ca-747a-11e8-95c8-1d92bdbf3bbf.png)

**Comment by jjsty1e** [comment]
发现是系统兼容性问题，目前已修复，你可以再试试 @ahmczsy
